service: searcher-germany

provider:
  name: aws
  runtime: java11

package:
  artifact: build/distributions/searcher-germany-0.0.1.zip

functions:
  http:
    # 256 was still a bit more sluggish, 512 made it usable
    memorySize: 512
    handler: de.spinscale.lambda.http.Handler
    events:
      - http:
          path: location
          method: post
